---
- hosts: localhost
  tasks:
    - name: Get public IP from environment variable
      ansible.builtin.set_fact:
        public_ip: "{{ lookup('env', 'JENKINS_VM_HOST') }}"

    - name: Replace placeholder in inventory file
      ansible.builtin.shell: sed -i "s|<placeholder_app>|{{ public_ip }}|g" ./Ansible/inventory

    - name: Display the modified inventory file
      ansible.builtin.command: cat ./Ansible/inventory
      register: inventory_content

    - name: Print inventory content
      debug:
        msg: "{{ inventory_content.stdout }}"

    - name: Get private key from environment variable
      ansible.builtin.set_fact:
        private_key: "{{ lookup('env', 'SSH_PRIVATE_KEY') }}"

    - name: Save private key to file
      ansible.builtin.copy:
        content: "{{ private_key }}"
        dest: ./Ansible/myKey.pem
        mode: '0400'
- hosts: all
  become_user: root
  become: true
  tasks:
    - name: Install pip3 and unzip
      changed_when: not ansible_check_mode
      apt:
        update_cache: yes
        pkg:
        - python3-pip
        - unzip
      register: result
      until: result is not failed
      retries: 5
      delay: 5

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true
    - name: Install Docker module for Python
      pip:
        name: docker
    - name: Pull the Jenkins Docker image
      docker_image:
        name: "samgabrail/jenkins-tf-vault-ansible:latest"
        source: pull
        state: present
        force_source: yes
    - name: Change file ownership, group and permissions
      file:
        path: /home/ubuntu/jenkins_data
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu
    - name: Create Jenkins container
      docker_container:
        name: "jenkins"
        image: "samgabrail/jenkins-tf-vault-ansible:latest"
        state: started
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /home/ubuntu/jenkins_data:/var/jenkins_home
