---
- hosts: all
  become_user: root
  become: true
  tasks:
    - name: Download get-pip.py script
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip3 using Python
      command: python3 /tmp/get-pip.py
    - name: Install pip3 and unzip
      apt:
        update_cache: yes
        pkg:
          - unzip
      register: result
      until: result is not failed
      retries: 5
      delay: 5
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: Update apt and install docker.io
      apt:
        name: docker.io
        state: latest
        update_cache: true
    - name: Install Docker module for Python
      pip:
        name: docker
    - name: Pull the Jenkins Docker image
      docker_image:
        name: "samgabrail/jenkins-tf-vault-ansible:latest"
        source: pull
        state: present
        force_source: yes
    - name: Change file ownership, group and permissions
      file:
        path: /home/ubuntu/jenkins_data
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu
    - name: Create Jenkins container
      docker_container:
        name: "jenkins"
        image: "samgabrail/jenkins-tf-vault-ansible:latest"
        state: started
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /home/ubuntu/jenkins_data:/var/jenkins_home