---
- hosts: all
  become_user: root
  become: true
  tasks:
    - name: Enable universe repository (for Ubuntu/Debian)
      apt_repository:
        repo: "ppa:deadsnakes/ppa"
        state: present
    - name: Install Python and pip
      apt:
        update_cache: yes
        pkg: "{{ item }}"
        state: present
      become: true
      loop:
        - python3
        - python3-pip
    - name: Install unzip
      apt:
        update_cache: yes
        pkg:
          - unzip
      register: result
      until: result is not failed
      retries: 5
      delay: 5
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Download and run Docker install script
      shell: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh

    - name: Install docker Python package
      pip:
        name: docker
    - name: Pull the Jenkins Docker image
      docker_image:
        name: "samgabrail/jenkins-tf-vault-ansible:latest"
        source: pull
        state: present
        force_source: yes
    - name: Change file ownership, group and permissions
      file:
        path: /home/ubuntu/jenkins_data
        state: directory
        recurse: yes
        owner: ubuntu
        group: ubuntu
    - name: Create Jenkins container
      docker_container:
        name: "jenkins"
        image: "samgabrail/jenkins-tf-vault-ansible:latest"
        state: started
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /home/ubuntu/jenkins_data:/var/jenkins_home